name: dart_first
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0-188.0.dev

dependencies:
  args: ^2.5.0
  mysql1: ^0.10.1   # Add this line to include the MySQL package

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
